#ifndef _CTL_CODE_DEF_H_
#define _CTL_CODE_DEF_H_

#ifndef CTL_CODE
#include <WinIoCtl.h>
#endif

#define ARITHMETIC_CODE_BUFFER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define ARITHMETIC_CODE_DIRECT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define ARITHMETIC_CODE_NEITHER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define SSDTHOOK_CODE_BUFFER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SSDTINLINEHOOK_CODE_BUFFER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif